# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate
from config.database import con, getCurrentUser
#from Settings import *

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GroupBoxProductDetails = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBoxProductDetails.setGeometry(QtCore.QRect(20, 450, 1241, 231))
        self.GroupBoxProductDetails.setMinimumSize(QtCore.QSize(1241, 0))
        self.GroupBoxProductDetails.setMaximumSize(QtCore.QSize(1241, 380))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GroupBoxProductDetails.setFont(font)
        self.GroupBoxProductDetails.setStyleSheet("color: rgb(224, 27, 36);\n" "border: 2px solid black; ")
        self.GroupBoxProductDetails.setObjectName("GroupBoxProductDetails")
        self.Label_5 = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.Label_5.setGeometry(QtCore.QRect(10, 20, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_5.setFont(font)
        self.Label_5.setStyleSheet("color: rgb(255,255,255);")
        self.Label_5.setObjectName("Label_5")
        self.product_name = QtWidgets.QComboBox(self.GroupBoxProductDetails)
        self.product_name.setGeometry(QtCore.QRect(10, 50, 501, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.product_name.setFont(font)
        self.product_name.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);")
        product_name = self.fetch_product_names()
        self.product_name.addItem("None")
        self.product_name.addItems(product_name)
        self.product_name.setObjectName("product_name")
        self.product_name.currentIndexChanged.connect(self.selected_pname)
        self.Label_13 = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.Label_13.setGeometry(QtCore.QRect(550, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_13.setFont(font)
        self.Label_13.setStyleSheet("color: rgb(255,255,255);")
        self.Label_13.setObjectName("Label_13")
        self.product_code = QtWidgets.QComboBox(self.GroupBoxProductDetails)
        self.product_code.setGeometry(QtCore.QRect(550, 50, 461, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.product_code.setFont(font)
        self.product_code.setStyleSheet("color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        product_code = self.fetch_product_code()
        self.product_code.addItem("None")
        self.product_code.addItems(product_code)
        self.product_code.currentIndexChanged.connect(self.selected_code)
        self.product_code.setObjectName("product_code")
        self.minimum_qty_label = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.minimum_qty_label.setGeometry(QtCore.QRect(1050, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.minimum_qty_label.setFont(font)
        self.minimum_qty_label.setStyleSheet("color: rgb(255,255,255);")
        self.minimum_qty_label.setObjectName("minimum_qty_label")
        self.min_qty = QtWidgets.QLineEdit(self.GroupBoxProductDetails)
        self.min_qty.setGeometry(QtCore.QRect(1050, 130, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.min_qty.setFont(font)
        self.min_qty.setReadOnly(True)
        self.min_qty.setStyleSheet("color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.min_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.min_qty.setObjectName("min_qty")
        self.max_qty = QtWidgets.QLineEdit(self.GroupBoxProductDetails)
        self.max_qty.setGeometry(QtCore.QRect(1050, 50, 151, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.max_qty.setFont(font)
        self.max_qty.setReadOnly(True)
        self.max_qty.setStyleSheet("color: rgb(0, 0, 0);\n""background-color: rgb(255, 255, 255);")
        self.max_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.max_qty.setObjectName("max_qty")
        self.maximum_qty_label = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.maximum_qty_label.setGeometry(QtCore.QRect(1050, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maximum_qty_label.setFont(font)
        self.maximum_qty_label.setStyleSheet("color: rgb(255,255,255);")
        self.maximum_qty_label.setObjectName("maximum_qty_label")
        self.Label_9 = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.Label_9.setGeometry(QtCore.QRect(10, 100, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_9.setFont(font)
        self.Label_9.setStyleSheet("color: rgb(255,255,255);")
        self.Label_9.setObjectName("Label_9")
        self.Label_15 = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.Label_15.setGeometry(QtCore.QRect(550, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Label_15.setFont(font)
        self.Label_15.setStyleSheet("color: rgb(255,255,255);")
        self.Label_15.setObjectName("Label_15")
        self.supplier_name = QtWidgets.QComboBox(self.GroupBoxProductDetails)
        self.supplier_name.setGeometry(QtCore.QRect(550, 130, 461, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.supplier_name.setFont(font)
        self.supplier_name.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);")
        supplier_name = self.fetch_supplier_name()
        self.supplier_name.addItem("None")
        self.supplier_name.addItems(supplier_name)
        self.supplier_name.setObjectName("supplier_name")
        self.customer_name = QtWidgets.QComboBox(self.GroupBoxProductDetails)
        self.customer_name.setGeometry(QtCore.QRect(10, 130, 501, 50))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.customer_name.setFont(font)
        self.customer_name.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);")
        customer_names = self.fetch_customer_name()
        self.customer_name.addItem("None")
        self.customer_name.addItems(customer_names)
        self.customer_name.setObjectName("customer_name")
        self.Label_Records = QtWidgets.QLabel(self.GroupBoxProductDetails)
        self.Label_Records.setGeometry(QtCore.QRect(10, 190, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Records.setFont(font)
        self.Label_Records.setStyleSheet("color: rgb(224, 27, 36);")
        self.Label_Records.setObjectName("Label_Records")
        self.Under_label = QtWidgets.QLabel(self.centralwidget)
        self.Under_label.setGeometry(QtCore.QRect(20, 30, 181, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_label.setFont(font)
        self.Under_label.setStyleSheet("color: rgb(255, 255, 0);")
        self.Under_label.setObjectName("Under_label")
        self.Range_label = QtWidgets.QLabel(self.centralwidget)
        self.Range_label.setGeometry(QtCore.QRect(440, 30, 181, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range_label.setFont(font)
        self.Range_label.setStyleSheet("color: rgb(33, 247, 9);")
        self.Range_label.setObjectName("Range_label")
        self.Over_label = QtWidgets.QLabel(self.centralwidget)
        self.Over_label.setGeometry(QtCore.QRect(850, 30, 161, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over_label.setFont(font)
        self.Over_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.Over_label.setObjectName("Over_label")
        self.Under1 = QtWidgets.QPushButton(self.centralwidget)
        self.Under1.setGeometry(QtCore.QRect(10, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under1.setFont(font)
        self.Under1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under1.setText("")
        self.Under1.setFlat(False)
        self.Under1.setObjectName("Under1")
        self.Under2 = QtWidgets.QPushButton(self.centralwidget)
        self.Under2.setGeometry(QtCore.QRect(50, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under2.setFont(font)
        self.Under2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under2.setText("")
        self.Under2.setFlat(False)
        self.Under2.setObjectName("Under2")
        self.Under3 = QtWidgets.QPushButton(self.centralwidget)
        self.Under3.setGeometry(QtCore.QRect(90, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under3.setFont(font)
        self.Under3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under3.setText("")
        self.Under3.setFlat(False)
        self.Under3.setObjectName("Under3")
        self.Under4 = QtWidgets.QPushButton(self.centralwidget)
        self.Under4.setGeometry(QtCore.QRect(130, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under4.setFont(font)
        self.Under4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under4.setText("")
        self.Under4.setFlat(False)
        self.Under4.setObjectName("Under4")
        self.Under5 = QtWidgets.QPushButton(self.centralwidget)
        self.Under5.setGeometry(QtCore.QRect(170, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under5.setFont(font)
        self.Under5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under5.setText("")
        self.Under5.setFlat(False)
        self.Under5.setObjectName("Under5")
        self.Under_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Under_8.setGeometry(QtCore.QRect(290, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_8.setFont(font)
        self.Under_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under_8.setText("")
        self.Under_8.setFlat(False)
        self.Under_8.setObjectName("Under_8")
        self.Under_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Under_9.setGeometry(QtCore.QRect(330, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_9.setFont(font)
        self.Under_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under_9.setText("")
        self.Under_9.setFlat(False)
        self.Under_9.setObjectName("Under_9")
        self.Under_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Under_6.setGeometry(QtCore.QRect(210, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_6.setFont(font)
        self.Under_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under_6.setText("")
        self.Under_6.setFlat(False)
        self.Under_6.setObjectName("Under_6")
        self.Under_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Under_7.setGeometry(QtCore.QRect(250, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_7.setFont(font)
        self.Under_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under_7.setText("")
        self.Under_7.setFlat(False)
        self.Under_7.setObjectName("Under_7")
        self.Under10 = QtWidgets.QPushButton(self.centralwidget)
        self.Under10.setGeometry(QtCore.QRect(370, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under10.setFont(font)
        self.Under10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Under10.setText("")
        self.Under10.setFlat(False)
        self.Under10.setObjectName("Under10")
        self.Range3 = QtWidgets.QPushButton(self.centralwidget)
        self.Range3.setGeometry(QtCore.QRect(510, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range3.setFont(font)
        self.Range3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range3.setText("")
        self.Range3.setFlat(False)
        self.Range3.setObjectName("Range3")
        self.Range4 = QtWidgets.QPushButton(self.centralwidget)
        self.Range4.setGeometry(QtCore.QRect(550, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range4.setFont(font)
        self.Range4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range4.setText("")
        self.Range4.setFlat(False)
        self.Range4.setObjectName("Range4")
        self.Range1 = QtWidgets.QPushButton(self.centralwidget)
        self.Range1.setGeometry(QtCore.QRect(430, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range1.setFont(font)
        self.Range1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range1.setText("")
        self.Range1.setFlat(False)
        self.Range1.setObjectName("Range1")
        self.Range7 = QtWidgets.QPushButton(self.centralwidget)
        self.Range7.setGeometry(QtCore.QRect(670, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range7.setFont(font)
        self.Range7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range7.setText("")
        self.Range7.setFlat(False)
        self.Range7.setObjectName("Range7")
        self.ButtonTare_11 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTare_11.setGeometry(QtCore.QRect(470, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonTare_11.setFont(font)
        self.ButtonTare_11.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonTare_11.setText("")
        self.ButtonTare_11.setFlat(False)
        self.ButtonTare_11.setObjectName("ButtonTare_11")
        self.Range9 = QtWidgets.QPushButton(self.centralwidget)
        self.Range9.setGeometry(QtCore.QRect(750, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range9.setFont(font)
        self.Range9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range9.setText("")
        self.Range9.setFlat(False)
        self.Range9.setObjectName("Range9")
        self.Range6 = QtWidgets.QPushButton(self.centralwidget)
        self.Range6.setGeometry(QtCore.QRect(630, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range6.setFont(font)
        self.Range6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range6.setText("")
        self.Range6.setFlat(False)
        self.Range6.setObjectName("Range6")
        self.Range10 = QtWidgets.QPushButton(self.centralwidget)
        self.Range10.setGeometry(QtCore.QRect(790, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range10.setFont(font)
        self.Range10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range10.setText("")
        self.Range10.setFlat(False)
        self.Range10.setObjectName("Range10")
        self.Range05 = QtWidgets.QPushButton(self.centralwidget)
        self.Range05.setGeometry(QtCore.QRect(590, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range05.setFont(font)
        self.Range05.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range05.setText("")
        self.Range05.setFlat(False)
        self.Range05.setObjectName("Range05")
        self.Range8 = QtWidgets.QPushButton(self.centralwidget)
        self.Range8.setGeometry(QtCore.QRect(710, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range8.setFont(font)
        self.Range8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Range8.setText("")
        self.Range8.setFlat(False)
        self.Range8.setObjectName("Range8")
        self.Over3 = QtWidgets.QPushButton(self.centralwidget)
        self.Over3.setGeometry(QtCore.QRect(930, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over3.setFont(font)
        self.Over3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over3.setText("")
        self.Over3.setFlat(False)
        self.Over3.setObjectName("Over3")
        self.Over4 = QtWidgets.QPushButton(self.centralwidget)
        self.Over4.setGeometry(QtCore.QRect(970, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over4.setFont(font)
        self.Over4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over4.setText("")
        self.Over4.setFlat(False)
        self.Over4.setObjectName("Over4")
        self.Over1 = QtWidgets.QPushButton(self.centralwidget)
        self.Over1.setGeometry(QtCore.QRect(850, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over1.setFont(font)
        self.Over1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over1.setText("")
        self.Over1.setFlat(False)
        self.Over1.setObjectName("Over1")
        self.Over7 = QtWidgets.QPushButton(self.centralwidget)
        self.Over7.setGeometry(QtCore.QRect(1090, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over7.setFont(font)
        self.Over7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over7.setText("")
        self.Over7.setFlat(False)
        self.Over7.setObjectName("Over7")
        self.Over2 = QtWidgets.QPushButton(self.centralwidget)
        self.Over2.setGeometry(QtCore.QRect(890, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over2.setFont(font)
        self.Over2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"      
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over2.setText("")
        self.Over2.setFlat(False)
        self.Over2.setObjectName("Over2")
        self.Over9 = QtWidgets.QPushButton(self.centralwidget)
        self.Over9.setGeometry(QtCore.QRect(1170, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over9.setFont(font)
        self.Over9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over9.setText("")
        self.Over9.setFlat(False)
        self.Over9.setObjectName("Over9")
        self.Over6 = QtWidgets.QPushButton(self.centralwidget)
        self.Over6.setGeometry(QtCore.QRect(1050, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over6.setFont(font)
        self.Over6.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over6.setText("")
        self.Over6.setFlat(False)
        self.Over6.setObjectName("Over6")
        self.Over10 = QtWidgets.QPushButton(self.centralwidget)
        self.Over10.setGeometry(QtCore.QRect(1210, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over10.setFont(font)
        self.Over10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over10.setText("")
        self.Over10.setFlat(False)
        self.Over10.setObjectName("Over10")
        self.Over5 = QtWidgets.QPushButton(self.centralwidget)
        self.Over5.setGeometry(QtCore.QRect(1010, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over5.setFont(font)
        self.Over5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over5.setText("")
        self.Over5.setFlat(False)
        self.Over5.setObjectName("Over5")
        self.Over8 = QtWidgets.QPushButton(self.centralwidget)
        self.Over8.setGeometry(QtCore.QRect(1130, 90, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over8.setFont(font)
        self.Over8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.Over8.setText("")
        self.Over8.setFlat(False)
        self.Over8.setObjectName("Over8")
        self.Under_weight = QtWidgets.QLabel(self.centralwidget)
        self.Under_weight.setGeometry(QtCore.QRect(200, 30, 211, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Under_weight.setFont(font)
        self.Under_weight.setStyleSheet("color: rgb(255, 255, 0);")
        self.Under_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Under_weight.setObjectName("Under_weight")
        self.Range_weight = QtWidgets.QLabel(self.centralwidget)
        self.Range_weight.setGeometry(QtCore.QRect(630, 30, 191, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Range_weight.setFont(font)
        self.Range_weight.setStyleSheet("color: rgb(33, 247, 9);")
        self.Range_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Range_weight.setObjectName("Range_weight")
        self.Over_weight = QtWidgets.QLabel(self.centralwidget)
        self.Over_weight.setGeometry(QtCore.QRect(1040, 30, 211, 42))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Over_weight.setFont(font)
        self.Over_weight.setStyleSheet("color: rgb(255, 0, 0);")
        self.Over_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Over_weight.setObjectName("Over_weight")
        self.ButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSave.setGeometry(QtCore.QRect(1090, 690, 171, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonSave.setFont(font)
        self.ButtonSave.setStyleSheet("background-color: rgb(33, 184, 22);\n"
"color: rgb(255, 255, 255);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonSave.setFlat(False)
        self.ButtonSave.setObjectName("ButtonSave")
        self.ButtonUnitWeigth = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonUnitWeigth.setGeometry(QtCore.QRect(400, 690, 130, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonUnitWeigth.setFont(font)
        self.ButtonUnitWeigth.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonUnitWeigth.setFlat(False)
        self.ButtonUnitWeigth.setObjectName("ButtonUnitWeigth")
        self.ButtonBatch = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBatch.setGeometry(QtCore.QRect(680, 690, 140, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonBatch.setFont(font)
        self.ButtonBatch.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonBatch.setFlat(False)
        self.ButtonBatch.setObjectName("ButtonBatch")
        self.ButtonQuantity = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonQuantity.setGeometry(QtCore.QRect(540, 690, 130, 90))
        self.ButtonQuantity.setCheckable(True)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonQuantity.setFont(font)
        self.ButtonQuantity.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonQuantity.setFlat(False)
        self.ButtonQuantity.clicked.connect(self.quantitybtpress)
        self.ButtonQuantity.setObjectName("ButtonQuantity")
        self.ButtonMenu = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonMenu.setGeometry(QtCore.QRect(120, 690, 130, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonMenu.setFont(font)
        self.ButtonMenu.setCheckable(True)
        self.ButtonMenu.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonMenu.setFlat(False)
        self.ButtonMenu.setObjectName("ButtonMenu")
        #self.ButtonMenu.clicked.connect(self.gotoscreen)
        self.ButtonPLU = QtWidgets.QPushButton(self.centralwidget) 
        self.ButtonPLU.setGeometry(QtCore.QRect(260, 690, 130, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonPLU.setFont(font)
        self.ButtonPLU.setCheckable(True)
        self.ButtonPLU.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonPLU.setFlat(False)
        self.ButtonPLU.setObjectName("ButtonPLU")
        self.GroupBoxWeight_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupBoxWeight_2.setGeometry(QtCore.QRect(20, 150, 1241, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GroupBoxWeight_2.setFont(font)
        self.GroupBoxWeight_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.GroupBoxWeight_2.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px black; ")
        self.GroupBoxWeight_2.setTitle("")
        self.GroupBoxWeight_2.setObjectName("GroupBoxWeight_2")
        self.Main_weight = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.Main_weight.setGeometry(QtCore.QRect(10, 0, 661, 221))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(109)
        font.setBold(True)
        font.setWeight(75)
        self.Main_weight.setFont(font)
        self.Main_weight.setStyleSheet("color: rgb(33, 247, 9);")
        self.Main_weight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Main_weight.setObjectName("Main_weight")
        self.Constant1 = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.Constant1.setGeometry(QtCore.QRect(860, 10, 341, 92))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.Constant1.setFont(font)
        self.Constant1.setStyleSheet("color: rgb(33, 247, 9);")
        self.Constant1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Constant1.setObjectName("Constant1")
        self.Constant2 = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.Constant2.setGeometry(QtCore.QRect(900, 120, 301, 60))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.Constant2.setFont(font)
        self.Constant2.setStyleSheet("color: rgb(33, 247, 9);")
        self.Constant2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Constant2.setObjectName("Constant2")
        self.label_2 = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.label_2.setGeometry(QtCore.QRect(0, 230, 911, 51))
        self.label_2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.LabelLoadUnload = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.LabelLoadUnload.setGeometry(QtCore.QRect(10, 240, 131, 27))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LabelLoadUnload.setFont(font)
        self.LabelLoadUnload.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.LabelLoadUnload.setObjectName("LabelLoadUnload")
        self.LabelDateTime = QtWidgets.QLabel(self.GroupBoxWeight_2)

        self.LabelDateTime.setGeometry(QtCore.QRect(540, 240, 361, 27))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LabelDateTime.setFont(font)
        self.LabelDateTime.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        
        self.LabelDateTime.setObjectName("LabelDateTime")
        self.LabelDateTime.setText("Nidhi")
        self.LabelAddress = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.LabelAddress.setText("00000000000")
        self.LabelAddress.setGeometry(QtCore.QRect(180, 240, 301, 27))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LabelAddress.setFont(font)
        self.LabelAddress.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);")
        self.LabelAddress.setObjectName("LabelAddress")
        self.Main_weight_kg = QtWidgets.QLabel(self.GroupBoxWeight_2)
        self.Main_weight_kg.setGeometry(QtCore.QRect(690, 80, 111, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonTare = QtWidgets.QPushButton(self.GroupBoxWeight_2)
        self.ButtonTare.setGeometry(QtCore.QRect(940, 200, 141, 81))

        self.Main_weight_kg.setFont(font)
        self.Main_weight_kg.setStyleSheet("color: rgb(33, 247, 9);")
        self.Main_weight_kg.setObjectName("Main_weight_kg")

        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonTare.setFont(font)
        self.ButtonTare.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(245, 194, 17);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonTare.setFlat(False)
        self.ButtonTare.setObjectName("ButtonTare")
        self.ButtonZero = QtWidgets.QPushButton(self.GroupBoxWeight_2)
        self.ButtonZero.setGeometry(QtCore.QRect(1090, 200, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonZero.setFont(font)
        self.ButtonZero.setStyleSheet("background-color: rgb(192, 97, 203);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonZero.setFlat(False)
        self.ButtonZero.setObjectName("ButtonZero")
        # self.ButtonZero_4 = QtWidgets.QPushButton(self.GroupBoxWeight_2)
        # self.ButtonZero_4.setGeometry(QtCore.QRect(810, 180, 91, 41))
        # font = QtGui.QFont()
        # font.setPointSize(15)
        # font.setBold(True)
        # font.setWeight(75)
        # self.ButtonZero_4.setFont(font)
        # self.ButtonZero_4.setStyleSheet("color: rgb(0, 0, 0);")
        # self.ButtonZero_4.setText("")
        # self.ButtonZero_4.setFlat(False)
        # self.ButtonZero_4.setObjectName("ButtonZero_4")
        self.ButtonClear = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonClear.setGeometry(QtCore.QRect(830, 690, 140, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonClear.setFont(font)
        self.ButtonClear.setText("asad")
        self.ButtonClear.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonClear.setFlat(False)
        self.ButtonClear.clicked.connect(self.clear)
        self.ButtonClear.setObjectName("ButtonClear")
        self.ButtonForward = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonForward.setGeometry(QtCore.QRect(980, 690, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonForward.setFont(font)
        self.ButtonForward.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonForward.setFlat(False)
        self.ButtonForward.setObjectName("ButtonForward")
        self.ButtonBackward = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBackward.setGeometry(QtCore.QRect(10, 690, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonBackward.setFont(font)
        self.ButtonBackward.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        self.ButtonBackward.setFlat(False)
        self.ButtonBackward.setObjectName("ButtonBackward")
        self.ButtonPrint = self.create_button(self.centralwidget, 680, 690, 140, 90, "HIDDEN1", "PRINT", "background-color: rgb(24, 90, 130);\nborder-style: outset;\nborder-width: 2px;\nborder-radius: 15px;\ncolor: rgb(255, 255, 255);\nborder-color: black;\npadding: 4px;")
        self.ButtonPrint.setObjectName("ButtonPrint")
        self.ButtonReport = self.create_button(self.centralwidget, 830, 690, 140, 90, "HIDDEN2", "REPORT", "background-color: rgb(24, 90, 130);\nborder-style: outset;\nborder-width: 2px;\nborder-radius: 15px;\ncolor: rgb(255, 255, 255);\nborder-color: black;\npadding: 4px;")
        self.ButtonReport.setObjectName("ButtonReport")
        self.ButtonPrint.hide()
        self.ButtonReport.hide()
        self.buttons=[]
        self.buttons = [
            self.ButtonMenu, self.ButtonPLU, self.ButtonUnitWeigth,
            self.ButtonQuantity, self.ButtonBatch, self.ButtonClear,
            self.ButtonPrint, self.ButtonReport
        ]

        MainWindow.setCentralWidget(self.centralwidget)
        self.btvalue = 0
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.ButtonForward.clicked.connect(self.show_hidden_buttons)
        self.ButtonBackward.clicked.connect(self.hide_hidden_buttons)

    def create_button(self, parent, x, y, width, height, name, text, style):
        button = QtWidgets.QPushButton(parent)
        button.setGeometry(QtCore.QRect(x, y, width, height))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        button.setFont(font)
        button.setStyleSheet(style)
        button.setFlat(False)
        button.setObjectName(name)
        button.setText(text)
        return button

    def show_hidden_buttons(self):
        self.ButtonPrint.show()
        self.ButtonReport.show()
        self.update_button_positions(forward=True)

    def hide_hidden_buttons(self):
        self.ButtonPrint.hide()
        self.ButtonReport.hide()
        self.update_button_positions(forward=False)

    def update_button_positions(self, forward):
        if forward:
            self.ButtonMenu.hide()
            self.ButtonPLU.hide()
            self.ButtonUnitWeigth.setGeometry(120, 690, 130, 90)
            self.ButtonQuantity.setGeometry(260, 690, 130, 90)
            self.ButtonBatch.setGeometry(400, 690, 130, 90)
            self.ButtonClear.setGeometry(540, 690, 130, 90)
        else:
            self.ButtonMenu.show()
            self.ButtonPLU.show()
            self.ButtonMenu.setGeometry(120, 690, 130, 90)
            self.ButtonPLU.setGeometry(260, 690, 130, 90)
            self.ButtonUnitWeigth.setGeometry(400, 690, 130, 90)
            self.ButtonQuantity.setGeometry(540, 690, 130, 90)
            self.ButtonBatch.setGeometry(680, 690, 140, 90)
            self.ButtonClear.setGeometry(830, 690, 140, 90)
        #     positions = [-500, -370, -240, -110, 20, 160, -500, -370]
        
        # for i, button in enumerate(self.buttons):
        #     if button.isVisible():
        #         button.setGeometry(positions[i], 690, 130, 90)
 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GroupBoxProductDetails.setTitle(_translate("MainWindow", "PRODUCT DETAILS"))
        self.Label_5.setText(_translate("MainWindow", "Product Name"))
        self.Label_13.setText(_translate("MainWindow", "Product Code"))
        self.minimum_qty_label.setText(_translate("MainWindow", "Mimimum QTY"))
        self.min_qty.setText(_translate("MainWindow", "0"))
        self.min_qty.setPlaceholderText(_translate("MainWindow", "0"))
        self.max_qty.setText(_translate("MainWindow", "0"))
        self.max_qty.setPlaceholderText(_translate("MainWindow", "0"))
        self.maximum_qty_label.setText(_translate("MainWindow", "Maximum QTY"))
        self.Label_9.setText(_translate("MainWindow", "Customer Name"))
        self.Label_15.setText(_translate("MainWindow", "Supplier Name"))
        self.Label_Records.setText(_translate("MainWindow", "RECORDS : 0"))
        self.Under_label.setText(_translate("MainWindow", "UNDER"))
        self.Range_label.setText(_translate("MainWindow", "RANGE"))
        self.Over_label.setText(_translate("MainWindow", "OVER"))
        self.Under_weight.setText(_translate("MainWindow", "111.000"))
        self.Range_weight.setText(_translate("MainWindow", "1.000"))
        self.Over_weight.setText(_translate("MainWindow", "115.000"))
        self.ButtonSave.setText(_translate("MainWindow", "SAVE"))
        self.ButtonUnitWeigth.setText(_translate("MainWindow", "UNIT "))
        self.ButtonBatch.setText(_translate("MainWindow", " BATCH "))
        self.ButtonQuantity.setText(_translate("MainWindow", "QTY"))
        self.ButtonMenu.setText(_translate("MainWindow", "MENU"))
        self.ButtonPLU.setText(_translate("MainWindow", "PLU"))
        #self.Main_weight.setText(_translate("MainWindow", "20000.0"))
        self.Constant1.setText(_translate("MainWindow", "11000"))
        self.Constant2.setText(_translate("MainWindow", "1300.000"))
        self.LabelLoadUnload.setText(_translate("MainWindow", "Unload"))
        self.LabelDateTime.setText(_translate("MainWindow", "Time"))
        current_date = QDate.currentDate()
        self.LabelDateTime.setText(current_date.toString())
        self.LabelAddress.setText(_translate("MainWindow", "IP : 255.255.255.255"))
        self.ButtonTare.setText(_translate("MainWindow", "TARE"))
        self.ButtonZero.setText(_translate("MainWindow", "ZERO"))
        self.ButtonClear.setText(_translate("MainWindow", "CLEAR"))
        self.ButtonForward.setText(_translate("MainWindow", ">"))
        self.ButtonBackward.setText(_translate("MainWindow", "<"))
        self.Main_weight_kg.setText(_translate("MainWindow", "Kg"))

        
    def readWeight(self):
        self.Main_weight.setText("10000.0")
        nweight=float(self.Main_weight.text())
        maxqty=int(self.max_qty.text())
        unitweight=nweight/maxqty
        funitweight=f"{unitweight:.2f}"
        self.Constant2.setText(f"{unitweight:.2f}")
        self.Constant1.setText(str(float(funitweight)*maxqty))
        
            
#     def getproductcode(self):
#         pro_code=self.product_code.currentText()
#         return pro_code
        
            
                
            
        
    def fetch_product_names(self):
        cur = con.cursor()
        q1 = "select product_name from product"
        cur.execute(q1)
        names = cur.fetchall()
        cur.close()
        return [name[0] for name in names]

    def fetch_product_code(self):
        cur = con.cursor()
        q1 = "select product_code from product"
        cur.execute(q1)
        codes = cur.fetchall()
        cur.close()
        return [code[0] for code in codes]
    
    def selected_code(self):
        selected_code = self.product_code.currentText()
        if selected_code == "None":
                self.min_qty.setText(str(0))
                self.max_qty.setText(str(0))
        else:
                cur = con.cursor()
                q1 = f"select min_quantity, max_quantity, product_name from product where product_code = {selected_code}"
                cur.execute(q1)
                result = cur.fetchone()
                cur.close()
                min_qty, max_qty, product_name = result
                self.min_qty.setText(str(min_qty))
                self.max_qty.setText(str(max_qty))
                self.product_name.setCurrentText(product_name)
                self.readWeight()

    def selected_pname(self):
        selected_name = self.product_name.currentText()
        if selected_name == "None":
                self.min_qty.setText(str(0))
                self.max_qty.setText(str(0))
        else:
                cur = con.cursor()
                q1 = "select min_quantity, max_quantity, product_code from product where product_name = %s"
                cur.execute(q1,(selected_name,))
                result = cur.fetchall()[0]
                cur.close()
                min_qty, max_qty, product_code = result
                self.min_qty.setText(str(min_qty))
                self.max_qty.setText(str(max_qty))
                self.product_code.setCurrentText(product_code)

    def fetch_customer_name(self):
        cur = con.cursor()
        q1 = "select customer_name from customer"
        cur.execute(q1)
        names = cur.fetchall()
        cur.close()
        return [name[0] for name in names]

    def fetch_supplier_name(self):
        cur = con.cursor()
        q1 = "select supplier_name from supplier"
        cur.execute(q1)
        names = cur.fetchall()
        cur.close()
        return [name[0] for name in names]
    
    def clear(self):
        self.product_name.setCurrentIndex(0)
        self.product_code.setCurrentIndex(0)
        self.customer_name.setCurrentIndex(0)
        self.supplier_name.setCurrentIndex(0)
        self.min_qty.setText(str(0))
        self.max_qty.setText(str(0))

        self.btvalue = 0
    def quantitybtpress(self):
        if self.ButtonQuantity.isChecked():
                self.max_qty.setReadOnly(False)
                self.min_qty.setReadOnly(False)
                self.ButtonQuantity.setFocus()
                self.ButtonQuantity.setStyleSheet("background-color: Green;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
        else:
                cur=con.cursor()
                curvaluemin = int(self.min_qty.text())
                curvaluemax = int(self.max_qty.text())
                code = self.product_code.currentText()
                q1 = "update product set min_quantity = %s, max_quantity =%s  where product_code = %s"
                cur.execute(q1,(curvaluemin,curvaluemax,code))
                self.max_qty.setReadOnly(True)
                self.min_qty.setReadOnly(True)
                self.ButtonQuantity.setStyleSheet("background-color: rgb(24, 90, 130);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"border-color: black;\n"
"padding: 4px;")
                cur.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

